name: planear
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.6
  riverpod_lint: ^2.3.10 #
  hooks_riverpod: ^2.5.1 #상태관리자 도우미 해당 플젝에서 사용 안 됨
  riverpod: ^2.5.1 #상태관리자
  flutter_styled_toast: ^2.2.1 #달력 한글화
  gap: ^3.0.1 #편의성
  carousel_slider: ^4.2.1 #상점 카탈로그 옆으로 넘기기
  table_calendar: ^3.0.9 #캘린더
  flutter_secure_storage: ^9.2.2 #로컬 저장소
  http: ^1.2.1 #통신
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/icons/
    - assets/images/avatar/accessory/
    - assets/images/avatar/body/
    - assets/images/avatar/face/
    - assets/images/avatar/etc/
    - assets/images/avatar/lower_hair/
    - assets/images/avatar/pants/
    - assets/images/avatar/shoes/
    - assets/images/avatar/top/
    - assets/images/avatar/upper_hair/
    - assets/images/avatar/hair/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
